//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharePoint.IdentityService.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharePoint_IdentityService_ActiveDirectory {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharePoint_IdentityService_ActiveDirectory() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharePoint.IdentityService.Resources.SharePoint.IdentityService.ActiveDirectory", typeof(SharePoint_IdentityService_ActiveDirectory).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Domains list starting to load for &quot;{0}&quot;.
        /// </summary>
        internal static string E1000 {
            get {
                return ResourceManager.GetString("E1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Domains list successfully loaded for &quot;{0}&quot; : {1}:{2},{3} s.
        /// </summary>
        internal static string E1000B {
            get {
                return ResourceManager.GetString("E1000B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error loading forest &quot;{0}&quot;.
        /// </summary>
        internal static string E1001 {
            get {
                return ResourceManager.GetString("E1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error searching in Top Level Names &quot;{0}&quot;.
        /// </summary>
        internal static string E1020 {
            get {
                return ResourceManager.GetString("E1020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error loading child domain &quot;{0}&quot;.
        /// </summary>
        internal static string E1100 {
            get {
                return ResourceManager.GetString("E1100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error initializing domain &quot;{0}&quot;.
        /// </summary>
        internal static string E1100B {
            get {
                return ResourceManager.GetString("E1100B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error loading forest &quot;{0}&quot;.
        /// </summary>
        internal static string E1200 {
            get {
                return ResourceManager.GetString("E1200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error loading root forest !.
        /// </summary>
        internal static string E1500 {
            get {
                return ResourceManager.GetString("E1500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error loading trust relationships  !.
        /// </summary>
        internal static string E1501 {
            get {
                return ResourceManager.GetString("E1501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reload of domains list started for &quot;{0}&quot;.
        /// </summary>
        internal static string E1900 {
            get {
                return ResourceManager.GetString("E1900", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reload of domains list finished for &quot;{0}&quot; : {1}:{2},{3} s.
        /// </summary>
        internal static string E1900B {
            get {
                return ResourceManager.GetString("E1900B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reload of domains list form cache started for &quot;{0}&quot;.
        /// </summary>
        internal static string E1901 {
            get {
                return ResourceManager.GetString("E1901", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reload of domains form cache finished for &quot;{0}&quot; : {1}:{2},{3} s.
        /// </summary>
        internal static string E1901B {
            get {
                return ResourceManager.GetString("E1901B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error loading domains from cache !.
        /// </summary>
        internal static string E1902 {
            get {
                return ResourceManager.GetString("E1902", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error retreiving users in domain &quot;{0}&quot; with search pattern &quot;{1}&quot;.
        /// </summary>
        internal static string E2000 {
            get {
                return ResourceManager.GetString("E2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error filling searching in domain &quot;{0}&quot; with search pattern &quot;{1}&quot;.
        /// </summary>
        internal static string E2001 {
            get {
                return ResourceManager.GetString("E2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error retreiving user ({0}) properties in domain &quot;{1}&quot; with search pattern &quot;{2}&quot;.
        /// </summary>
        internal static string E2002 {
            get {
                return ResourceManager.GetString("E2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error searching in domain &quot;{0}&quot;.
        /// </summary>
        internal static string E2010 {
            get {
                return ResourceManager.GetString("E2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error searching in domain with free form &quot;{0}&quot;.
        /// </summary>
        internal static string E2010B {
            get {
                return ResourceManager.GetString("E2010B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error filling searching in domain &quot;{0}&quot;.
        /// </summary>
        internal static string E2010C {
            get {
                return ResourceManager.GetString("E2010C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error resolving groups in domain &quot;{0}&quot; with search pattern &quot;{1}&quot;.
        /// </summary>
        internal static string E2500 {
            get {
                return ResourceManager.GetString("E2500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error resolving identities in domain &quot;{0}&quot; with search pattern &quot;{1}&quot;.
        /// </summary>
        internal static string E2500B {
            get {
                return ResourceManager.GetString("E2500B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error retreiving groups in domain &quot;{0}&quot; with search pattern &quot;{1}&quot;.
        /// </summary>
        internal static string E2501 {
            get {
                return ResourceManager.GetString("E2501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error resolving identities in domain &quot;{0}&quot; with resolve pattern &quot;{1}&quot;.
        /// </summary>
        internal static string E2501B {
            get {
                return ResourceManager.GetString("E2501B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error retreiving group properties in domain &quot;{0}&quot; with search pattern &quot;{1}&quot;.
        /// </summary>
        internal static string E2502 {
            get {
                return ResourceManager.GetString("E2502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error resolving group properties in domain &quot;{0}&quot; with search pattern &quot;{1}&quot;.
        /// </summary>
        internal static string E2502B {
            get {
                return ResourceManager.GetString("E2502B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error retreiving user ({0}) properties in domain &quot;{1}&quot; with search pattern &quot;{2}&quot;.
        /// </summary>
        internal static string E2502C {
            get {
                return ResourceManager.GetString("E2502C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error resolving identity with search pattern &quot;{0}&quot;.
        /// </summary>
        internal static string E8001 {
            get {
                return ResourceManager.GetString("E8001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error Validating identity with search pattern &quot;{0}&quot;.
        /// </summary>
        internal static string E8001B {
            get {
                return ResourceManager.GetString("E8001B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid Group, objectGuid, objectSid, groupType, sAMAccountName are required !.
        /// </summary>
        internal static string INVGRP {
            get {
                return ResourceManager.GetString("INVGRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid User, userPrincipalName and sAMAccountName properties are required !.
        /// </summary>
        internal static string INVUSER {
            get {
                return ResourceManager.GetString("INVUSER", resourceCulture);
            }
        }
    }
}
