//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharePoint.IdentityService.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharePoint_IdentityService_Application {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharePoint_IdentityService_Application() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharePoint.IdentityService.Resources.SharePoint.IdentityService.Application", typeof(SharePoint_IdentityService_Application).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in FillSearch with pattern &quot;{0}&quot; on domain &quot;{1}&quot;.
        /// </summary>
        internal static string E20001 {
            get {
                return ResourceManager.GetString("E20001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in FillResolve with pattern &quot;{0}&quot;.
        /// </summary>
        internal static string E20002 {
            get {
                return ResourceManager.GetString("E20002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in FillValidate with pattern &quot;{0}&quot;.
        /// </summary>
        internal static string E20003 {
            get {
                return ResourceManager.GetString("E20003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in FillHierarchy with node &quot;{0}&quot;.
        /// </summary>
        internal static string E20004 {
            get {
                return ResourceManager.GetString("E20004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in FillHierarchy.
        /// </summary>
        internal static string E20004B {
            get {
                return ResourceManager.GetString("E20004B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in FillBadDomains.
        /// </summary>
        internal static string E20005 {
            get {
                return ResourceManager.GetString("E20005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in Reload.
        /// </summary>
        internal static string E20006 {
            get {
                return ResourceManager.GetString("E20006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in LaunchStartCommand.
        /// </summary>
        internal static string E20007 {
            get {
                return ResourceManager.GetString("E20007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in FillAdditionalClaims.
        /// </summary>
        internal static string E20008 {
            get {
                return ResourceManager.GetString("E20008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in FillGeneralParameters.
        /// </summary>
        internal static string E20009 {
            get {
                return ResourceManager.GetString("E20009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in FillClaimsProviderParameters.
        /// </summary>
        internal static string E20010 {
            get {
                return ResourceManager.GetString("E20010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This job warm up SharePoint Identity Service Applications. (for slow and weak infrastructure).
        /// </summary>
        internal static string E20101 {
            get {
                return ResourceManager.GetString("E20101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This job reload all SharePoint Identity Service Applications. (for slow and weak infrastructure).
        /// </summary>
        internal static string E20102 {
            get {
                return ResourceManager.GetString("E20102", resourceCulture);
            }
        }
    }
}
