//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharePoint.IdentityService.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharePoint_IdentityService_ClaimsProvider {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharePoint_IdentityService_ClaimsProvider() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharePoint.IdentityService.Resources.SharePoint.IdentityService.ClaimsProvider", typeof(SharePoint_IdentityService_ClaimsProvider).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in FillSearch with pattern &quot;{0}&quot;.
        /// </summary>
        internal static string E07000 {
            get {
                return ResourceManager.GetString("E07000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in FillResolve (SPClaim) with pattern &quot;{0}&quot;.
        /// </summary>
        internal static string E07001 {
            get {
                return ResourceManager.GetString("E07001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in FillResolve (String) with pattern &quot;{0}&quot;.
        /// </summary>
        internal static string E07002 {
            get {
                return ResourceManager.GetString("E07002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in FillHierarchy.
        /// </summary>
        internal static string E07003 {
            get {
                return ResourceManager.GetString("E07003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid entity type in FillResolve (Claims).
        /// </summary>
        internal static string E07004 {
            get {
                return ResourceManager.GetString("E07004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid entity type in FillSearch with pattern &quot;{0}&quot;.
        /// </summary>
        internal static string E07005 {
            get {
                return ResourceManager.GetString("E07005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid entity type in FillResolve (Text) with input &quot;{0}&quot;.
        /// </summary>
        internal static string E07006 {
            get {
                return ResourceManager.GetString("E07006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid entity type in FillHierachy.
        /// </summary>
        internal static string E07007 {
            get {
                return ResourceManager.GetString("E07007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No domains founds in the repository ! please verify your configuration !.
        /// </summary>
        internal static string E07008 {
            get {
                return ResourceManager.GetString("E07008", resourceCulture);
            }
        }
    }
}
