//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharePoint.IdentityService.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharePoint_IdentityService_Administration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharePoint_IdentityService_Administration() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharePoint.IdentityService.Resources.SharePoint.IdentityService.Administration", typeof(SharePoint_IdentityService_Administration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage your connections, set specific settings for each entity or domain.
        /// </summary>
        internal static string CNXFORMSECTIONDESC {
            get {
                return ResourceManager.GetString("CNXFORMSECTIONDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repositories or directories connections.
        /// </summary>
        internal static string CNXINPUTCONTROLTITLE {
            get {
                return ResourceManager.GetString("CNXINPUTCONTROLTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repositories connections.
        /// </summary>
        internal static string CNXTFORMSECTIONTITLE {
            get {
                return ResourceManager.GetString("CNXTFORMSECTIONTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A connection name is required !.
        /// </summary>
        internal static string CNXVALIDATORNAMEMESSAGE {
            get {
                return ResourceManager.GetString("CNXVALIDATORNAMEMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A password is required !.
        /// </summary>
        internal static string CNXVALIDATORPWDMESSAGE {
            get {
                return ResourceManager.GetString("CNXVALIDATORPWDMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The number of lines retreived must be between 1 and 9999.
        /// </summary>
        internal static string CNXVALIDATORROWSMESSAGE {
            get {
                return ResourceManager.GetString("CNXVALIDATORROWSMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Timeout must be between 1 and 90 seconds.
        /// </summary>
        internal static string CNXVALIDATORTIMEOUTPOSMESSAGE {
            get {
                return ResourceManager.GetString("CNXVALIDATORTIMEOUTPOSMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A user name is required !.
        /// </summary>
        internal static string CNXVALIDATORUSERMESSAGE {
            get {
                return ResourceManager.GetString("CNXVALIDATORUSERMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must specify the attibutes store extension associated with your claim provider.
        /// </summary>
        internal static string DLLFORMSECTIONDESC {
            get {
                return ResourceManager.GetString("DLLFORMSECTIONDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attributes store extensions.
        /// </summary>
        internal static string DLLFORMSECTIONTITLE {
            get {
                return ResourceManager.GetString("DLLFORMSECTIONTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attributes store extensions.
        /// </summary>
        internal static string DLLINPUTCONTROLTITLE {
            get {
                return ResourceManager.GetString("DLLINPUTCONTROLTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid Assembly or Component type. \nThis reference can&apos;t be trusted.
        /// </summary>
        internal static string DLLVALIDATORADDMESSAGE {
            get {
                return ResourceManager.GetString("DLLVALIDATORADDMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assembly Full Description must be set.
        /// </summary>
        internal static string DLLVALIDATORASSEMBLYMESSAGE {
            get {
                return ResourceManager.GetString("DLLVALIDATORASSEMBLYMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must implement SharePoint.IdentityService.Core.IIdentityServiceClaimsAugmenter in your assembly and deploy it..
        /// </summary>
        internal static string DLLVALIDATORDETMESSAGE1 {
            get {
                return ResourceManager.GetString("DLLVALIDATORDETMESSAGE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must implement SharePoint.IdentityService.Core.IWrapper in your assembly and deploy it.
        /// </summary>
        internal static string DLLVALIDATORDETMESSAGE2 {
            get {
                return ResourceManager.GetString("DLLVALIDATORDETMESSAGE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type Description must be set.
        /// </summary>
        internal static string DLLVALIDATORTYPEMESSAGE {
            get {
                return ResourceManager.GetString("DLLVALIDATORTYPEMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Register assemblies for accessing repositories, specify extensions for active directory, SQL, Web, SAP and others (Active Directory Forest is the default).
        /// </summary>
        internal static string ENTFORMSECTIONDESC {
            get {
                return ResourceManager.GetString("ENTFORMSECTIONDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entities and domains.
        /// </summary>
        internal static string ENTFORMSECTIONTITLE {
            get {
                return ResourceManager.GetString("ENTFORMSECTIONTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entities and domains.
        /// </summary>
        internal static string ENTINPUTCONTROLTITLE {
            get {
                return ResourceManager.GetString("ENTINPUTCONTROLTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The domain description must be specified, this value will be displayed in the peoplepicker.
        /// </summary>
        internal static string ENTVALIDATORDISPLAYMESSAGE {
            get {
                return ResourceManager.GetString("ENTVALIDATORDISPLAYMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The DNS value must be specified, this value is used by the attributes store extensions.
        /// </summary>
        internal static string ENTVALIDATORDNSMESSAGE {
            get {
                return ResourceManager.GetString("ENTVALIDATORDNSMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The value must be between 1 and 99.
        /// </summary>
        internal static string ENTVALIDATORPOSMESSAGE {
            get {
                return ResourceManager.GetString("ENTVALIDATORPOSMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear application cache.
        /// </summary>
        internal static string MANAGECLEARCACHE {
            get {
                return ResourceManager.GetString("MANAGECLEARCACHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connections management for application {0}.
        /// </summary>
        internal static string MANAGECONNECTIONSDESC {
            get {
                return ResourceManager.GetString("MANAGECONNECTIONSDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This page allows you to change settings of {0}.
        /// </summary>
        internal static string MANAGEDESC {
            get {
                return ResourceManager.GetString("MANAGEDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Driver management for apllication {0}.
        /// </summary>
        internal static string MANAGEDLLDESC {
            get {
                return ResourceManager.GetString("MANAGEDLLDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entities and domains management for application {0}.
        /// </summary>
        internal static string MANAGEENTITIESDESC {
            get {
                return ResourceManager.GetString("MANAGEENTITIESDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage connections, set domains connections parameters for some or each of them.
        /// </summary>
        internal static string MANAGEIDCONNECTIONSDESC {
            get {
                return ResourceManager.GetString("MANAGEIDCONNECTIONSDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repositories connections.
        /// </summary>
        internal static string MANAGEIDCONNECTIONSTEXT {
            get {
                return ResourceManager.GetString("MANAGEIDCONNECTIONSTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage entities, define allowed domains, entities that must be displayed inside the peoplepicker, choose thier display names and positions.
        /// </summary>
        internal static string MANAGEIDENTITIESDESC {
            get {
                return ResourceManager.GetString("MANAGEIDENTITIESDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entities and domains.
        /// </summary>
        internal static string MANAGEIDENTITIESTEXT {
            get {
                return ResourceManager.GetString("MANAGEIDENTITIESTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Register assemblies for accessing repositories, specify extensions for active directory, SQL, Web, SAP and others (Active Directory Forest is the default).
        /// </summary>
        internal static string MANAGEIDEXTENSIONSDESC {
            get {
                return ResourceManager.GetString("MANAGEIDEXTENSIONSDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attributes store extensions.
        /// </summary>
        internal static string MANAGEIDEXTENSIONSTEXT {
            get {
                return ResourceManager.GetString("MANAGEIDEXTENSIONSTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage general settings, cache timeout, display modes, display of photos, query mode, etc....
        /// </summary>
        internal static string MANAGEIDPARAMSDESC {
            get {
                return ResourceManager.GetString("MANAGEIDPARAMSDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à General settings.
        /// </summary>
        internal static string MANAGEIDPARAMSTEXT {
            get {
                return ResourceManager.GetString("MANAGEIDPARAMSTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Genral parameters management for application {0}.
        /// </summary>
        internal static string MANAGEPARAMETERSDESC {
            get {
                return ResourceManager.GetString("MANAGEPARAMETERSDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh application parameters.
        /// </summary>
        internal static string MANAGEREFRESH {
            get {
                return ResourceManager.GetString("MANAGEREFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back.
        /// </summary>
        internal static string MANAGERETURN {
            get {
                return ResourceManager.GetString("MANAGERETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application management : {0}.
        /// </summary>
        internal static string MANAGETITLE {
            get {
                return ResourceManager.GetString("MANAGETITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cache duration for domains metadatas (mn).
        /// </summary>
        internal static string PRMCACHEDURATION {
            get {
                return ResourceManager.GetString("PRMCACHEDURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Claims Provider Description.
        /// </summary>
        internal static string PRMCLAIMPROVIDERDESC {
            get {
                return ResourceManager.GetString("PRMCLAIMPROVIDERDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Claims Provider Name.
        /// </summary>
        internal static string PRMCLAIMPROVIDERNAME {
            get {
                return ResourceManager.GetString("PRMCLAIMPROVIDERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Claims Provider.
        /// </summary>
        internal static string PRMCLAIMPROVIDERTITLE {
            get {
                return ResourceManager.GetString("PRMCLAIMPROVIDERTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Claims Provider Mode.
        /// </summary>
        internal static string PRMCLAIMPROVIDERTYPE {
            get {
                return ResourceManager.GetString("PRMCLAIMPROVIDERTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Display Name and Email.
        /// </summary>
        internal static string PRMCLAIMSDROPDESCEMAIL {
            get {
                return ResourceManager.GetString("PRMCLAIMSDROPDESCEMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Display Name.
        /// </summary>
        internal static string PRMCLAIMSDROPDISPLAYNAME {
            get {
                return ResourceManager.GetString("PRMCLAIMSDROPDISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email address.
        /// </summary>
        internal static string PRMCLAIMSDROPEMAIL {
            get {
                return ResourceManager.GetString("PRMCLAIMSDROPEMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Federated Claims.
        /// </summary>
        internal static string PRMCLAIMSDROPFED {
            get {
                return ResourceManager.GetString("PRMCLAIMSDROPFED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Role Name.
        /// </summary>
        internal static string PRMCLAIMSDROPROLE {
            get {
                return ResourceManager.GetString("PRMCLAIMSDROPROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SAM account name.
        /// </summary>
        internal static string PRMCLAIMSDROPSAM {
            get {
                return ResourceManager.GetString("PRMCLAIMSDROPSAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SID Windows.
        /// </summary>
        internal static string PRMCLAIMSDROPSID {
            get {
                return ResourceManager.GetString("PRMCLAIMSDROPSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User Principal Name.
        /// </summary>
        internal static string PRMCLAIMSDROPUPN {
            get {
                return ResourceManager.GetString("PRMCLAIMSDROPUPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Windows Claims.
        /// </summary>
        internal static string PRMCLAIMSDROPWIN {
            get {
                return ResourceManager.GetString("PRMCLAIMSDROPWIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identity Claim for Users.
        /// </summary>
        internal static string PRMCLAIMSIDENTITY {
            get {
                return ResourceManager.GetString("PRMCLAIMSIDENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identity Claim value for group and roles.
        /// </summary>
        internal static string PRMCLAIMSIDENTITYROLES {
            get {
                return ResourceManager.GetString("PRMCLAIMSIDENTITYROLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identity claim used to identify groups/roles.
        /// </summary>
        internal static string PRMCLAIMSIDENTITYROLESVALUE {
            get {
                return ResourceManager.GetString("PRMCLAIMSIDENTITYROLESVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identity claim used to identify users.
        /// </summary>
        internal static string PRMCLAIMSIDENTITYVALUE {
            get {
                return ResourceManager.GetString("PRMCLAIMSIDENTITYVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        internal static string PRMCLAIMSMODEDESC {
            get {
                return ResourceManager.GetString("PRMCLAIMSMODEDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Claim displayed in PeoplePicker.
        /// </summary>
        internal static string PRMCLAIMSPEOPLEPICKER {
            get {
                return ResourceManager.GetString("PRMCLAIMSPEOPLEPICKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Left Queries ( litteral *).
        /// </summary>
        internal static string PRMCLAIMSQRYAFT {
            get {
                return ResourceManager.GetString("PRMCLAIMSQRYAFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Right Queries (* litteral ).
        /// </summary>
        internal static string PRMCLAIMSQRYBEF {
            get {
                return ResourceManager.GetString("PRMCLAIMSQRYBEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full Queries (* litteral *).
        /// </summary>
        internal static string PRMCLAIMSQRYFULL {
            get {
                return ResourceManager.GetString("PRMCLAIMSQRYFULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Strict Queries ( litteral ).
        /// </summary>
        internal static string PRMCLAIMSQRYSTRICT {
            get {
                return ResourceManager.GetString("PRMCLAIMSQRYSTRICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Claim displayed in SharePoint.
        /// </summary>
        internal static string PRMCLAIMSSHAREPOINT {
            get {
                return ResourceManager.GetString("PRMCLAIMSSHAREPOINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Claims.
        /// </summary>
        internal static string PRMCLAIMSTITLE {
            get {
                return ResourceManager.GetString("PRMCLAIMSTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description must be filled !.
        /// </summary>
        internal static string PRMERRORCLAIMDESC {
            get {
                return ResourceManager.GetString("PRMERRORCLAIMDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User Identity claim namespace is required !.
        /// </summary>
        internal static string PRMERRORCLAIMIDENTITYVALUE {
            get {
                return ResourceManager.GetString("PRMERRORCLAIMIDENTITYVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Claims Provider Name must be filled !.
        /// </summary>
        internal static string PRMERRORCLAIMNAME {
            get {
                return ResourceManager.GetString("PRMERRORCLAIMNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identity claim namespace is required !.
        /// </summary>
        internal static string PRMERRORCLAIMROLESVALUE {
            get {
                return ResourceManager.GetString("PRMERRORCLAIMROLESVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Minimum 0 (disabled) and Maximum 1440 minutes !.
        /// </summary>
        internal static string PRMERRORTIMEOUT {
            get {
                return ResourceManager.GetString("PRMERRORTIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage parameters and optimization skills.
        /// </summary>
        internal static string PRMFORMSECTIONDESC {
            get {
                return ResourceManager.GetString("PRMFORMSECTIONDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Global parameters.
        /// </summary>
        internal static string PRMFORMSECTIONTITLE {
            get {
                return ResourceManager.GetString("PRMFORMSECTIONTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trusted Identity Provider.
        /// </summary>
        internal static string PRMIDENTITYPROVIDERDESC {
            get {
                return ResourceManager.GetString("PRMIDENTITYPROVIDERDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identity Provider.
        /// </summary>
        internal static string PRMIDENTITYPROVIDERTITLE {
            get {
                return ResourceManager.GetString("PRMIDENTITYPROVIDERTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Global parameters.
        /// </summary>
        internal static string PRMINPUTCONTROLTITLE {
            get {
                return ResourceManager.GetString("PRMINPUTCONTROLTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Queries Mode.
        /// </summary>
        internal static string PRMQUERIESMODE {
            get {
                return ResourceManager.GetString("PRMQUERIESMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repositories.
        /// </summary>
        internal static string PRMREPOSITORYDESC {
            get {
                return ResourceManager.GetString("PRMREPOSITORYDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search on user display name.
        /// </summary>
        internal static string PRMSEARCHDISPLAYNAME {
            get {
                return ResourceManager.GetString("PRMSEARCHDISPLAYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search on user mail addresses.
        /// </summary>
        internal static string PRMSEARCHEMAILS {
            get {
                return ResourceManager.GetString("PRMSEARCHEMAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show images in PeoplePicker.
        /// </summary>
        internal static string PRMSHOWPEOPLEPICKERIMG {
            get {
                return ResourceManager.GetString("PRMSHOWPEOPLEPICKERIMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show System accounts (local).
        /// </summary>
        internal static string PRMSHOWSYSTEMACCOUNTS {
            get {
                return ResourceManager.GetString("PRMSHOWSYSTEMACCOUNTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Specify the name, database, application pool for this service application.
        /// </summary>
        internal static string SVCAPPDESC {
            get {
                return ResourceManager.GetString("SVCAPPDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Always visible (IsUsedByDefault).
        /// </summary>
        internal static string SVCCPFORMSECTIONALWAYS {
            get {
                return ResourceManager.GetString("SVCCPFORMSECTIONALWAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Specify the name, description and visibility of your claim provider..
        /// </summary>
        internal static string SVCCPFORMSECTIONDESC {
            get {
                return ResourceManager.GetString("SVCCPFORMSECTIONDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Claim provider description.
        /// </summary>
        internal static string SVCCPFORMSECTIONDESC2 {
            get {
                return ResourceManager.GetString("SVCCPFORMSECTIONDESC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Claim provider description is required !.
        /// </summary>
        internal static string SVCCPFORMSECTIONDESCREQUIRED {
            get {
                return ResourceManager.GetString("SVCCPFORMSECTIONDESCREQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Claim provider display label.
        /// </summary>
        internal static string SVCCPFORMSECTIONLABEL {
            get {
                return ResourceManager.GetString("SVCCPFORMSECTIONLABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Claim provider description (SPClaimProvider).
        /// </summary>
        internal static string SVCCPFORMSECTIONLABEL2 {
            get {
                return ResourceManager.GetString("SVCCPFORMSECTIONLABEL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Claim provider display label is required !.
        /// </summary>
        internal static string SVCCPFORMSECTIONLABELREQUIRED {
            get {
                return ResourceManager.GetString("SVCCPFORMSECTIONLABELREQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Claim Provider.
        /// </summary>
        internal static string SVCCPFORMSECTIONTITLE {
            get {
                return ResourceManager.GetString("SVCCPFORMSECTIONTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Claim provider visibility.
        /// </summary>
        internal static string SVCCPFORMSECTIONVISIBILITY {
            get {
                return ResourceManager.GetString("SVCCPFORMSECTIONVISIBILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database options.
        /// </summary>
        internal static string SVCDBOPTTITLE {
            get {
                return ResourceManager.GetString("SVCDBOPTTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Re-use database.
        /// </summary>
        internal static string SVCDBREUSEDESC {
            get {
                return ResourceManager.GetString("SVCDBREUSEDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Re-use existing database.
        /// </summary>
        internal static string SVCDBREUSELABEL {
            get {
                return ResourceManager.GetString("SVCDBREUSELABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Specify if you you want to use an existing database.
        /// </summary>
        internal static string SVCDBSUBTITLE {
            get {
                return ResourceManager.GetString("SVCDBSUBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database.
        /// </summary>
        internal static string SVCDBTITLE {
            get {
                return ResourceManager.GetString("SVCDBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name of service application.
        /// </summary>
        internal static string SVCFORMSECTIONDESC {
            get {
                return ResourceManager.GetString("SVCFORMSECTIONDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The application name is required !.
        /// </summary>
        internal static string SVCFORMSECTIONREQUIRED {
            get {
                return ResourceManager.GetString("SVCFORMSECTIONREQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This application name is always used !.
        /// </summary>
        internal static string SVCFORMSECTIONUSED {
            get {
                return ResourceManager.GetString("SVCFORMSECTIONUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identity Provider.
        /// </summary>
        internal static string SVCIDPECTIONTITLE {
            get {
                return ResourceManager.GetString("SVCIDPECTIONTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Specify the identity provider associated with your claim provider..
        /// </summary>
        internal static string SVCIDPECTIONTITLEDESC {
            get {
                return ResourceManager.GetString("SVCIDPECTIONTITLEDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identity provider type.
        /// </summary>
        internal static string SVCIDPECTIONTYPE {
            get {
                return ResourceManager.GetString("SVCIDPECTIONTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must select a valid identity provider !.
        /// </summary>
        internal static string SVCIDPSELECTREQUIRED {
            get {
                return ResourceManager.GetString("SVCIDPSELECTREQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Active Directory Claims..
        /// </summary>
        internal static string SVCTRUSTEDLABELAD {
            get {
                return ResourceManager.GetString("SVCTRUSTEDLABELAD", resourceCulture);
            }
        }
    }
}
